version: '3.1'

services:
  postgresql:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
      # POSTGRES_USER: postgres
      # POSTGRES_DB: postgres
